spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5433/encore_users
    username: encore
    password: encore
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

server:
  port: 8084